name: Merge Deployment Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  determine-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run determine-environment-and-tag
        uses: ./.github/actions/determine-environment-and-tag.yaml
        id: determine-environment-and-tag

      - name: Set Outputs
        run: |
          echo "ENV=${{ steps.determine-environment-and-tag.outputs.env }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ steps.determine-environment-and-tag.outputs.image_tag }}" >> $GITHUB_ENV
  

  deploy-preprod:
    uses: ./.github/workflows/deploy-template.yml
    needs:
      - determine-environment-and-tag
    with:
      env: ${{ needs.determine-environment-and-tag.outputs.env }}

  tag-and-release:
    uses: ./.github/workflows/create-tag.yml
    with:
      branch_name: ${{ github.ref_name }}
      commit_message: ${{ github.event.head_commit.message }}
  
  deploy-prod:
    uses: ./.github/workflows/deploy-template.yaml
    needs:
      - tag-and-release
      - determine-environment-and-tag
    with:
      env: "prod"