name: Reusable set environment and tag workflow

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  determine-environment-and-tag:
      runs-on: ubuntu-latest
      outputs:
        ENV: ${{ steps.set-env.outputs.env }}
        IMAGE_TAG: ${{ steps.set-env.outputs.image_tag }}
      steps:
        - name: Determine environment and image tag
          id: set-env
          run: |
            if [[ "${GITHUB_REF}" == refs/heads/main || "${GITHUB_REF}" == refs/heads/master ]]; then
              echo "env=preprod" >> $GITHUB_ENV
              echo "::set-output name=env::preprod"
              echo "image_tag=main" >> $GITHUB_ENV
              echo "::set-output name=image_tag::main"
            elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              TAG_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')
              echo "env=prod" >> $GITHUB_ENV
              echo "::set-output name=env::prod"
              echo "image_tag=${TAG_NAME}" >> $GITHUB_ENV
              echo "::set-output name=image_tag::${TAG_NAME}"
            else
              BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')
              echo "env=dev" >> $GITHUB_ENV
              echo "::set-output name=env::dev"
              echo "image_tag=${BRANCH_NAME}" >> $GITHUB_ENV
              echo "::set-output name=image_tag::${BRANCH_NAME}"
            fi
