name: Reusable set environment and tag workflow

on:
  workflow_call:

jobs:
  determine-env-and-tag:
      runs-on: ubuntu-latest
      outputs:
        env: ${{ steps.set-env.outputs.env }}
        image_tag: ${{ steps.set-env.outputs.image_tag }}
      steps:
        - name: Determine environment and image tag
          id: vars
          run: |
            if [[ "${GITHUB_REF_NAME}" == "main" || "${GITHUB_REF_NAME}" == "master" ]]; then
              echo "env=preprod" >> "${GITHUB_OUTPUT}"
              echo "image_tag=main" >> "${GITHUB_OUTPUT}"
            elif [[ "${GITHUB_REF_NAME}" == v* ]]; then
              tag_name="${GITHUB_REF_NAME#v}"
              echo "env=prod" >> "${GITHUB_OUTPUT}"
              echo "image_tag=${tag_name}" >> "${GITHUB_OUTPUT}"
            else
              brunch_name="${GITHUB_REF_NAME}"
              echo "env=dev" >> "${GITHUB_OUTPUT}"
              echo "image_tag=${brunch_name}" >> "${GITHUB_OUTPUT}"
            fi
          env:
            GITHUB_REF_NAME: ${{ github.ref_name }}`