name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - refactor


env:
  TAG: counter
  VERSION: latest
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0


jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.TAG }}:${{ env.VERSION }}

      - name: Inspect
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.TAG }}:${{ env.VERSION }}