name: CI CD Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


env:
  IMAGE: counter
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0
  HELM_VERSION: 'v3.9.0'


jobs:
  determine-environment-and-tag:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.gen-output.outputs.env }}
      image_tag: ${{ steps.gen-output.outputs.image_tag }}
    steps:
      - name: Determine environment and image tag
        id: gen-output
        run: |
          # Determine environment and image tag based on the ref name
          if [[ "${GITHUB_REF_NAME}" == "main" || "${GITHUB_REF_NAME}" == "master" ]]; then
            env="preprod"
            image_tag="main"
          elif [[ "${GITHUB_REF_NAME}" == v* ]]; then
            env="prod"
            image_tag=$(echo "${GITHUB_REF_NAME}")
          else
            brunch_name=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]')
            env="dev"
            image_tag=${brunch_name}
          fi
          
          # Set outputs for the workflow
          echo "env=${env}" >> $GITHUB_OUTPUT
          echo "image_tag=${image_tag}" >> $GITHUB_OUTPUT
          
          # Print the values to the log for debugging
          echo "ENV=${env}"
          echo "IMAGE_TAG=${image_tag}"
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}`

  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Helm lint
        run: |
          helm lint counter-service-chart

  build:
    runs-on: ubuntu-latest
    needs:
      - lint-helm
      - determine-environment-and-tag
    outputs:
      lower_repo_name: ${{ steps.lowercase.outputs.lower_repo_name }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      IMAGE_TAG: ${{ needs.determine-environment-and-tag.outputs.env }}
      ENV: ${{ needs.determine-environment-and-tag.outputs.env }}"
    steps:
      - name: Convert Repository Name to Lowercase
        id: lowercase
        run: |
          # Convert the GITHUB_REPOSITORY to lowercase and set it as an environment variable
          lower_repo_name=${GITHUB_REPOSITORY@L}
          echo "LOWER_REPO_NAME=${lower_repo_name}" >> "${GITHUB_ENV}"
          echo "lower_repo_name=${lower_repo_name}" >> $GITHUB_OUTPUT

      - name: Print environment variables
        run: |
          echo "ENV=${{ env.IMAGE_TAG}}"
          echo "IMAGE_TAG=${{env.IMAGE_TAG}}"

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.LOWER_REPO_NAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Inspect
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.LOWER_REPO_NAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG}}

  package:
    needs: lint-helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-chart
          path: counter-service-chart/*.tgz  # Path to the packaged chart file

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-chart
          path: counter-service-chart/*.tgz

  deploy:
    runs-on: ubuntu-latest
    needs:
      - package
      - build
      - determine-environment-and-tag
    environment: AWS
    env:
      IMAGE_TAG: ${{ needs.determine-environment-and-tag.outputs.env }}
      ENV: ${{ needs.determine-environment-and-tag.outputs.env }}"
      LOWER_REPO_NAME:  ${{ needs.build.outputs.lower_repo_name }}"
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{vars.AWS_REGION}}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Helm upgrade/install
        run:  helm upgrade --install ${{ env.ENV }} counter-service-chart \
              --set image.repository=${{ env.REGISTRY }}/${{ env.LOWER_REPO_NAME }}/${{ env.IMAGE }} \
              --set image.tag=${{ env.IMAGE_TAG}}"
