name: CI CD Pipeline

on:
  push:
    branches:
      - '*'


env:
  TAG: counter
  VERSION: latest
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0


jobs:
  lint-helm:
    runs-on: ubuntu-latest
    needs: setup-helm
    steps:
      - uses: ./.github/workflows/setup-helm.yml
      - name: Helm lint
        run: |
          helm lint counter-service-chart

  package:
    needs: lint-helm
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-helm.yml
      - name: Package Helm chart
        run: |
          helm package counter-service-chart  # Path to your chart directory

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-chart
          path: counter-service-chart/*.tgz  # Path to the packaged chart file

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-chart
          path: counter-service-chart/*.tgz

  build:
    runs-on: ubuntu-latest
    needs: lint-helm
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Convert Repository Name to Lowercase
        id: lowercase
        run: |
          # Convert the GITHUB_REPOSITORY to lowercase and set it as an environment variable
          lowercase_repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "LOWER_REPO_NAME=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.LOWER_REPO_NAME }}/${{ env.TAG }}:${{ env.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Inspect
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.LOWER_REPO_NAME }}/${{ env.TAG }}:${{ env.VERSION }}